#############################################################################
# Makefile for building: project_mshukla
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Dec 18 03:29:46 2014
# Project:  project_mshukla.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile project_mshukla.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = LoginWindow.cpp \
		main.cpp \
		md5.cpp \
		Movie.cpp \
		MovieMenu.cpp \
		Netflix.cpp \
		NewUserWindow.cpp \
		RatingsWindow.cpp \
		User.cpp \
		UserChangeWindow.cpp \
		UserMenu.cpp \
		ViewAllRatings.cpp moc_LoginWindow.cpp \
		moc_MovieMenu.cpp \
		moc_NewUserWindow.cpp \
		moc_RatingsWindow.cpp \
		moc_UserChangeWindow.cpp \
		moc_UserMenu.cpp \
		moc_ViewAllRatingsWindow.cpp
OBJECTS       = LoginWindow.o \
		main.o \
		md5.o \
		Movie.o \
		MovieMenu.o \
		Netflix.o \
		NewUserWindow.o \
		RatingsWindow.o \
		User.o \
		UserChangeWindow.o \
		UserMenu.o \
		ViewAllRatings.o \
		moc_LoginWindow.o \
		moc_MovieMenu.o \
		moc_NewUserWindow.o \
		moc_RatingsWindow.o \
		moc_UserChangeWindow.o \
		moc_UserMenu.o \
		moc_ViewAllRatingsWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		project_mshukla.pro
QMAKE_TARGET  = project_mshukla
DESTDIR       = 
TARGET        = project_mshukla

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project_mshukla.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile project_mshukla.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project_mshukla.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project_mshukla1.0.0 || $(MKDIR) .tmp/project_mshukla1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project_mshukla1.0.0/ && $(COPY_FILE) --parents DLL.h LoginWindow.h md5.h Mergesort.h Movie.h MovieMenu.h Netflix.h NewUserWindow.h Queue.h RatingsWindow.h Set.h User.h UserChangeWindow.h UserMenu.h ViewAllRatingsWindow.h .tmp/project_mshukla1.0.0/ && $(COPY_FILE) --parents LoginWindow.cpp main.cpp md5.cpp Movie.cpp MovieMenu.cpp Netflix.cpp NewUserWindow.cpp RatingsWindow.cpp User.cpp UserChangeWindow.cpp UserMenu.cpp ViewAllRatings.cpp .tmp/project_mshukla1.0.0/ && (cd `dirname .tmp/project_mshukla1.0.0` && $(TAR) project_mshukla1.0.0.tar project_mshukla1.0.0 && $(COMPRESS) project_mshukla1.0.0.tar) && $(MOVE) `dirname .tmp/project_mshukla1.0.0`/project_mshukla1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project_mshukla1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_LoginWindow.cpp moc_MovieMenu.cpp moc_NewUserWindow.cpp moc_RatingsWindow.cpp moc_UserChangeWindow.cpp moc_UserMenu.cpp moc_ViewAllRatingsWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_LoginWindow.cpp moc_MovieMenu.cpp moc_NewUserWindow.cpp moc_RatingsWindow.cpp moc_UserChangeWindow.cpp moc_UserMenu.cpp moc_ViewAllRatingsWindow.cpp
moc_LoginWindow.cpp: Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		LoginWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LoginWindow.h -o moc_LoginWindow.cpp

moc_MovieMenu.cpp: Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		MovieMenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MovieMenu.h -o moc_MovieMenu.cpp

moc_NewUserWindow.cpp: Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		NewUserWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) NewUserWindow.h -o moc_NewUserWindow.cpp

moc_RatingsWindow.cpp: Movie.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		User.h \
		Queue.h \
		RatingsWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) RatingsWindow.h -o moc_RatingsWindow.cpp

moc_UserChangeWindow.cpp: Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		UserMenu.h \
		UserChangeWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UserChangeWindow.h -o moc_UserChangeWindow.cpp

moc_UserMenu.cpp: Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		UserMenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UserMenu.h -o moc_UserMenu.cpp

moc_ViewAllRatingsWindow.cpp: UserMenu.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		ViewAllRatingsWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ViewAllRatingsWindow.h -o moc_ViewAllRatingsWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

LoginWindow.o: LoginWindow.cpp LoginWindow.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		UserMenu.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginWindow.o LoginWindow.cpp

main.o: main.cpp LoginWindow.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

md5.o: md5.cpp md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o md5.o md5.cpp

Movie.o: Movie.cpp Movie.h \
		Set.h \
		DLL.h \
		Mergesort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o Movie.cpp

MovieMenu.o: MovieMenu.cpp MovieMenu.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		UserMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MovieMenu.o MovieMenu.cpp

Netflix.o: Netflix.cpp Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Netflix.o Netflix.cpp

NewUserWindow.o: NewUserWindow.cpp NewUserWindow.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		RatingsWindow.h \
		LoginWindow.h \
		UserMenu.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewUserWindow.o NewUserWindow.cpp

RatingsWindow.o: RatingsWindow.cpp RatingsWindow.h \
		Movie.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		User.h \
		Queue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RatingsWindow.o RatingsWindow.cpp

User.o: User.cpp User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

UserChangeWindow.o: UserChangeWindow.cpp UserChangeWindow.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		UserMenu.h \
		LoginWindow.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserChangeWindow.o UserChangeWindow.cpp

UserMenu.o: UserMenu.cpp UserMenu.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h \
		LoginWindow.h \
		MovieMenu.h \
		UserChangeWindow.h \
		ViewAllRatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserMenu.o UserMenu.cpp

ViewAllRatings.o: ViewAllRatings.cpp ViewAllRatingsWindow.h \
		UserMenu.h \
		Netflix.h \
		User.h \
		Set.h \
		DLL.h \
		Mergesort.h \
		Queue.h \
		Movie.h \
		NewUserWindow.h \
		RatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewAllRatings.o ViewAllRatings.cpp

moc_LoginWindow.o: moc_LoginWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginWindow.o moc_LoginWindow.cpp

moc_MovieMenu.o: moc_MovieMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MovieMenu.o moc_MovieMenu.cpp

moc_NewUserWindow.o: moc_NewUserWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewUserWindow.o moc_NewUserWindow.cpp

moc_RatingsWindow.o: moc_RatingsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RatingsWindow.o moc_RatingsWindow.cpp

moc_UserChangeWindow.o: moc_UserChangeWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UserChangeWindow.o moc_UserChangeWindow.cpp

moc_UserMenu.o: moc_UserMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UserMenu.o moc_UserMenu.cpp

moc_ViewAllRatingsWindow.o: moc_ViewAllRatingsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewAllRatingsWindow.o moc_ViewAllRatingsWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

